### ISSUE TITLE
Rename repository to "genart-template"

### ISSUE THREAD

**Issue by blwatkins** [brittni-and-the-polar-bear/genart-template#127]
Rename repository to "genart-template"

# Tasks
- [x] rename repository
- [x] fix all links in package.json
- [x] fix all links in README.md
- [x] update copyright template (optional)
